pipeline:
  test:
    image: python:2.7.11
    pull: true
    commands:
      - pip install -U Django${DJANGO_VERSION}
      - pip install -r requirements.test.txt
      - make test

matrix:
  DJANGO_VERSION:
    - <1.9
    - <2.0
