pipeline:
  test:
    image: python:2.7.11
    pull: true
    commands:
      - pip install -r requirements.test.txt
      - pip install -U "Django${DJANGO_VERSION}"
      - make test

matrix:
  DJANGO_VERSION:
    - <2.0
